// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJsWRFdqnB-iRIMtN0RZYy1Bv3l24Jejc',
    appId: '1:738391010072:web:4bf60e332c34b166ca0c6d',
    messagingSenderId: '738391010072',
    projectId: 'tokri-sem-three',
    authDomain: 'tokri-sem-three.firebaseapp.com',
    storageBucket: 'tokri-sem-three.appspot.com',
    measurementId: 'G-9932YS8S7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi7VzBpkTxNp63_vRh23y1oXBKebHXp88',
    appId: '1:738391010072:android:0686047ee9f624d4ca0c6d',
    messagingSenderId: '738391010072',
    projectId: 'tokri-sem-three',
    storageBucket: 'tokri-sem-three.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0iY45o9j0eQAvBwtkuYEzkr1d6fXREQ0',
    appId: '1:738391010072:ios:89d3d0c4c8533625ca0c6d',
    messagingSenderId: '738391010072',
    projectId: 'tokri-sem-three',
    storageBucket: 'tokri-sem-three.appspot.com',
    iosBundleId: 'com.example.tokriSemThree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0iY45o9j0eQAvBwtkuYEzkr1d6fXREQ0',
    appId: '1:738391010072:ios:9f04b014eaa28761ca0c6d',
    messagingSenderId: '738391010072',
    projectId: 'tokri-sem-three',
    storageBucket: 'tokri-sem-three.appspot.com',
    iosBundleId: 'com.example.tokriSemThree.RunnerTests',
  );
}
